# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "eartharoid"
license = "MIT"
licenselink = "https://github.com/eartharoid/eartharoid.me/blob/master/LICENSE"
description = "My Hugo theme"
homepage = "https://eartharoid.me/"
tags = ["bulma"]
features = ["darkmode"]
min_version = "0.41.0"

[author]
  name = "eartharoid"
  homepage = "https://eartharoid.me"

# If porting an existing theme
#[original]
#  name = ""
#  homepage = ""
#  repo = ""
